pipeline {
    agent {
        label 'nodejs'
    }
    parameters {
        booleanParam(name: 'RUN_FRONTEND_TESTS', defaultValue: true, description: 'Run frontend tests')
    }
    stages {
        stage('Tests') {
            parallel {
                stage('Backend Tests') {
                    steps {
                        dir('08-jenkinsfile/backend') {
                            sh 'node test.js'
                        }
                    }
                }
                stage('Frontend Tests') {
                    when {
                        expression { params.RUN_FRONTEND_TESTS }
                    }
                    steps {
                        dir('08-jenkinsfile/frontend') {
                            sh 'node test.js'
                        }
                    }
                }
            }
        }
    }
}
